=== Backend structure
We use three main packages to differentiate between the Controller and Services
that provide the REST API, the Data that holds no logic and the Service that
links the ProPay API to our application.

==== Package 'Controller'
The Controller package holds packages for each major task that needs to be
handled by our API.

===== General Structure and Oversight of recurring Subfolders
The Controllers are divided corresponding to their path in the API, meaning 
there is one package corresponding to its appearance in the API. This leads 
to a better oversight and easier divisions between the domains and their tasks.
Controller packages contain subfolders/subpackages for their API-path and for
 structuring purposes.


* *Controllers* are used to map the API-Path.

* *DTOs*
or Data Transfer Objects, are used to for post requests on the API. Since we 
often use post mappings in our API we need wrapper classes to work with the
RequestBodies in the HTTP-Bodies. A DTOs folder is always present in a package
containing a Controller dealing with post mappings.

* *Exception* 
Since we send custom responses to our frontend and do not want send general 
exceptions and errors to the frontend, we chose to use custom exceptions for 
more specific error handling and informing of the end user. These custom
exceptions are saved in the packages of the Controllers using these exceptions.

* *Services*
We try to separate the logic from the controller. For this purpose we use
Services which contain the Business-Logic for fRently. These contain the methods
and other services to implement the core features of our backend. They also
contain the repositories to correspond with the database, so we can have 
persistency.

* *IServices*
Since we try to follow the SOLID-Principles, we need to have interfaces for 
Dependency-Inversion. There exists one Interface for each Service and all 
Interfaces for a subpackage are collected in a IServices folder.

---

* *Borrow* has the subpackages Article, Inquiry and Transactions. 
The Article package deals with the role of the user as an borrower and returns
the available offers which one can borrow and if needed all available 
articles of a specific user. The articles are filtered so that a user can not
borrow their own article +
The Inquiry package is there so a user can create an inquiry if they are 
interested in borrowing it. It deals with creating inquiries and returning all 
open inquires of a user they have created. +
For already rented articles there is the Transaction package. The 
package returns all the transactions a Borrower has, meaning the stuff they
have rented and one can return an item and the transaction is being updated.
In addition deposit is freed and the fee is transferred to the lender.

* *Buy*
Buy allows an user to get all possible articles they could buy and gives them 
the possibility to buy a particular article. In this case the money is 
transferred from the buyer to the seller and the article is deleted.

* *Conflict*
If an item is returned in a bad condition or not returned at all, there is the
conflict center. If a user is an admin then they can get all transactions 
marked with conflict. After having externally talked with both parties, the
admin can now choose to either free the deposit or punish the borrower, 
transferring the deposit to the lender.

* *Lend*
Similar to Borrow, Lend contains an Article, Inquiry and Transaction
subpackage. +
Article gives the user the ability to upload a new article to be rented out 
and the option to update an already existing article. +
It also returns returns a list of all the currently enlisted articles a user 
has. + 
In inquiry a list of all open inquiries for articles, a user has, is sent. One can also accept and decline inquiries and if an inquiry
is accepted a new transfer object is created and saved. In both cases the 
inquiry is being updated. +
Transfer shows all Transactions for articles a lender has. Transfer also allows 
a user to update and finish a transaction if an item has been returned or 
mark a transaction as 'CONFLICT' if there are any problems with the returnment.

* *Response*
We use custom objects to transfer data with our frontend. This leads to more 
unified messaging and more expected behaviour. We always return a
FrentlyReponse. It contains either data or a FrentlyError. Just one of them 
is being set depending if an exception is thrown. All the different error types
 are also defined here.

* *Sell*
Sell allows the user to create items, to sell and update them if wanted.
An user also gets an overview of all the articles they offered to sell. 

* *Security*
Our API routes are secured with spring security using a JSON Web Token (JWT).
When the client logs into the application he receives a bearer token, now he has
to add the token to the authorisation header of all requests. This part is
handled by the javascript application which stores the token inside our redux
store and automatically sets it before calling the API. +
In the backend two filters handle the authorisation and authentication process.
The authorisation filter filters all requests and validates the existence and
validity of the token inside the request header and thus allows the request to
reach the destined controller. If the token is not valid the backend returns 403
 HTTP error. A token is valid for ten days. +
The authentication filter is used to issue the token to a user that wants to
login to the application, by validating username and password.

* *User*
The User package is the first one that is used if an user wants to use fRently.
With this package an user can sign-up for fRently. This results in an
ApplicationUser being created and saved as well as the creation of an ProPayUser,
 given the availability of ProPay. +
With the help of the User package an User can also view their own details and 
charge up their ProPay Account. +
Notifications for the user are also retrieved here.

==== Package 'Data'
The Data package holds all Classes with no logic.

* *Config*
holds only one class, the Config class which has a annotation that enables
database objects to automatically set the timestamp and updated variables.

* *Exceptions*
holds the NoSuchArticleException and NoSuchInquiryException which both extend
the FrentlyException. These are used in the Controller Package to tell the
frontend that something in the backend went wrong. We chose to put them here 
since, these exceptions deal with the Repository and are used by multiple\
 controller domains.

* *Models*
holds all Entities that saved in our database.
- ApplicationUser: Representing the User of fRently
- Article: Articles a User can either borrow/lend or buy/sell
- Inquiry: An Inquiry is created if a User wants to borrow an Article.
- Role: Representing the rights an ApplicationUser has. Important for conflict
center
- Transaction: If an Inquiry is accepted a Transaction is created, standing for 
the renting of the object.

* *Repositories*
Our Backend uses CRUD-Repositories to access and update our data objects in the
database. Most enquiries return lists with a specific type.

==== Package 'ProPay'
The ProPay Package holds everything that is related to the interaction with the
ProPay API.

* *Exceptions*
holds the ProPayConnectionException which extends FrentlyException and is
thrown by the ProPayService if the ProPay API is not found or the responses come
too slow.

* *IServices*
holds the interfaces of all the services that are defined in the Services
package. These are used for dependency inversion in all classes (mostly
controllers) that use these services.

* *Models*
holds the data objects that our application receives from ProPay and are used
by the ProPayService.
- MoneyTransfer objects are saved in a repository and are used to list all
money transfers that are made.
- ProPayAccount objects are used for the API calls and as they store specific
information.
- Reservation objects are also used to transfer information from the ProPay API.

* *Services*
holds all the services that are used to interface with the ProPay API. That is
mainly the ProPayService which does all the API calls.
- ProPayService uses RestTemplates to interface with the ProPay API. The Base-
URL that is used stands in the application.properties and though depend on
whether the develop configuration is on or not. Whenever money is transferred
the
- MoneyTransferService is used to create and save MoneyTransfers in the
database.
- ProPayApplicationUserService is used in the MoneyTransferService to set the
sender and receiver in the MoneyTransfer objects.

==== FrentlyBackendApplication
Starts our SpringBootApplication and declares the BCryptPasswordEncoder Bean
for Spring-Security.

==== Initializer
Fills the database with test data.

==== SwaggerConfig
Generates a Swagger API documentation reachable under
http://localhost:8080/swagger-ui.html#/[Swagger-UI] if the application is
running.
