language: java

sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2

before_install:
  # Docker Compose Install 
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up --build

#before_script:
#  - cd backend

#after_script:
#  - cd ..
#  - docker-compose stop
#  - docker-compose rm -f

