matrix:
  include:
    - language: java
      before_install:
        - cd backend
    - language: node_js
      before_install:
        - cd frontend
        - npm i -g npm@5.6.0
      node_js: "8.11.0"
      cache: npm

branches:
  only:
  - master
