= Softwareentwicklung im Team Blockpraktikum Team IllegalSkillsException
WS18/19
:icons: font
:icon-set: octicon

image::frontend/src/View/App/logo.svg[]


== Starting the project
=== As tester / non developer
To start the project simply run `docker-compose up`. This should start the docker compose, which starts all necessary components.
When the docker compose has finished setting up, the website should be available under the URL : `http://localhost:8080`.

=== As developer
TO start the project in dev mode the following things need to be done:

- Start propay
- Start the backend 
- Start the frontend

===== Starting propay
To start propay run the following command in any folder:

`docker run -p 8888:8888 propra/propay:latest`

===== Starting the backend
To start the backend, go into the backend folder and run the following command:



===== Starting the frontend
To start the frontend, go into the frontend folder and run the following commans:

`npm i`
`npm run start`

This should start the react dev server. If the login/register does not work, you probably need to remove the "/api" from the base URL in the file "/frontend/src/Services/urlConstants.js"
