package hhu.propra2.illegalskillsexception.frently.backend.Controller.Response;

public enum FrentlyErrorType {
    MISC,
    USER_NOT_FOUND,
    ARTICLE_NOT_AVAILABLE,
    INQUIRY_NOT_FOUND,
    INVALID_LENDING_PERIOD,
    NOT_SUCH_ARTICLE,
    NO_SUCH_SELL_ARTICLE,
    USER_ALREADY_EXISTING,
    INSUFFICIENT_FUNDS,
    PROPAY_CONNECTION,
    NO_SUCH_TRANSACTION,
    PENDING_INQUIRIES
    NOT_ENOUGH_MONEY,
    USER_IS_NOT_ADMIN,
}
